---
name: Docker Image CI

on:
  push:
    branches:
      - master
      - tested

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3
      - name: Build the Docker image
        run: make build-spamgourmet-clone
      - name: Run tests in docker
        run: make docker-test
