---
name: pre-commit

on:
  pull_request:
    branches:
        - master
        - devel
  push:
    branches: 
        - master
        - devel

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: install perltidy
        run: sudo apt-get install -y perltidy
      - uses: actions/setup-python@v2
      - uses: pre-commit/action@v3.0.0
        with:
          extra_args: --all-files --config .pre-commit-config-build.yaml
