---
name: Spamgourmet Overall Test

on:
  schedule:
    - cron: "36 03 24 * *"

  pull_request:
    branches:
      - master
      - devel
  push:
    branches:
      - master
      - devel

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v2
      - name: Run the tests
        run: make test
