---
name: Spamgourmet Overall Test

on:
  pull_request:
    branches:
      - master
      - devel
  push:
    branches:
      - master
      - devel

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Run the tests
        run: make test
